---
apiVersion: batch/v1
kind:       Job
metadata:
  name: hms-discovery-vault-loader-{{ .Release.Revision }}
spec:
  template:
    metadata:
        labels:
            app: hms-discovery-vault-loader
    spec:
      restartPolicy: OnFailure
      serviceAccountName: "jobs-watcher"
      containers:
        - name: hms-discovery-vault-loader
          env:
            - name: VAULT_ADDR
              value: "http://cray-vault.vault:8200"
            - name: VAULT_SKIP_VERIFY
              value: "true"
            - name: VAULT_REDFISH_BMC_DEFAULTS
              valueFrom:
                secretKeyRef:
                  name: cray-reds-credentials
                  key: vault_redfish_defaults
            - name: VAULT_REDFISH_SWITCH_DEFAULTS
              valueFrom:
                secretKeyRef:
                  name: cray-reds-credentials
                  key: vault_switch_defaults
          image: {{ .Values.image.repository }}:{{ .Values.global.appVersion }}
          command: ["vault_loader"]