{{- if .Values.vaultLoader.enabled }}
{{- if index .Values "sealedSecrets" -}}
{{- range $val := index .Values "sealedSecrets" }}
{{- if $val.kind }}
{{- if eq $val.kind "SealedSecret" }}
---
{{ toYaml $val }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
