apiVersion: batch/v1
kind: CronJob
metadata:
  name: hms-discovery
  labels:
    app: hms-discovery
spec:
  suspend: false
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app: hms-discovery
            cronjob-name: hms-discovery
        spec:
          containers:
            - name: hms-discovery
              image: {{ .Values.image.repository }}:{{ default .Values.global.appVersion .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: LOG_LEVEL
                  value: {{ .Values.discovery.logLevel | quote }}

                - name: SLS_URL
                  value: "http://cray-sls"
                - name: HSM_URL
                  value: "http://cray-smd"

                - name: DISCOVER_RIVER
                  value: {{ .Values.discovery.discoverRiverWithDHCP | quote }}
                - name: DISCOVER_MOUNTAIN
                  value: {{ .Values.discovery.discoverMountain | quote }}
                - name: DISCOVER_MANAGEMENT_NODES
                  value: {{ .Values.discovery.discoverManagementNodes | quote }}
                - name: DISCOVER_MANAGEMENT_VIRTUAL_NODES
                  value: {{ .Values.discovery.discoverManagementVirtualNodes | quote }}
                - name: REDISCOVER_FAILED_REDFISH_ENDPOINTS
                  value: {{ .Values.discovery.rediscoverFailedRedfishEndpoints | quote }}
                - name: POPULATE_MANAGEMENT_SWITCH_CREDENTIALS
                  value: {{ .Values.discovery.populateManagementSwitchCredentials | quote }}

                - name: VAULT_ADDR
                  value: "http://cray-vault.vault:8200"
                - name: VAULT_SKIP_VERIFY
                  value: "true"
                - name: VAULT_BASE_PATH
                  value: "secret"
              securityContext:
                runAsUser: 65534
                runAsGroup: 65534
                runAsNonRoot: true
          restartPolicy: Never
